export const projects = [
    {
        id: "portfolio",
        category: "main",
        overlineKey: "main_overline",
        titleKey: "portfolio.title",
        descriptionKey: "portfolio.description",
        reversed: false,
        primaryAction: { labelKey: "primaryAction", path: "portfolio" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.tommasoberti.com",
        },
        previewProps: {
            url: "https://www.tommasoberti.com",
            titleKey: "portfolio.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", level: 85 },
                { id: "mui", level: 80 },
                { id: "javascript", level: 90 },
                { id: "github", level: 65 },
                { id: "webstorm", level: 55 },
                { id: "caddy", level: 60 },
            ],
            roadmapIds: ["v1", "v2", "v3"],
        },
    },
    {
        id: "codexpane",
        category: "main",
        overlineKey: "main_overline",
        titleKey: "codexpane.title",
        descriptionKey: "codexpane.description",
        reversed: true,
        primaryAction: { labelKey: "primaryAction", path: "codexpane" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.codexpane.tommasoberti.com",
        },
        previewProps: {
            url: "https://www.codexpane.tommasoberti.com",
            titleKey: "codexpane.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", level: 85 },
                { id: "mui", level: 80 },
                { id: "javascript", level: 90 },
                { id: "github", level: 65 },
                { id: "webstorm", level: 55 },
                { id: "caddy", level: 60 },
                { id: "minisearch", level: 50 },
                { id: "tailwindcss", level: 10 },
                { id: "css", level: 15 },
            ],
            roadmapIds: ["v1", "v2", "v3", "v4"],
        },
    },
];