export const projects = [
    {
        id: "portfolio",
        category: "main",
        overlineKey: "main_project_overline",
        titleKey: "portfolio.title",
        descriptionKey: "portfolio.description",
        reversed: false,
        primaryAction: { labelKey: "primaryAction", path: "portfolio" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.tommasoberti.com",
        },
        githubHref: "https://github.com/tommaso-berti/tommaso-berti-portfolio",
        previewProps: {
            url: "https://www.tommasoberti.com",
            titleKey: "portfolio.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "javascript", roleKey: "application_logic", usageKey: "primary" },
                { id: "mui", roleKey: "design_system", usageKey: "primary" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3", "v4"],
        },
    },
    {
        id: "codexpane",
        category: "main",
        overlineKey: "main_project_overline",
        titleKey: "codexpane.title",
        descriptionKey: "codexpane.description",
        reversed: true,
        primaryAction: { labelKey: "primaryAction", path: "codexpane" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.codexpane.tommasoberti.com",
        },
        githubHref: "https://github.com/tommaso-berti/codexPane",
        previewProps: {
            url: "https://www.codexpane.tommasoberti.com",
            titleKey: "codexpane.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "javascript", roleKey: "application_logic", usageKey: "primary" },
                { id: "mui", roleKey: "design_system", usageKey: "primary" },
                { id: "tailwindcss", roleKey: "style_layer", usageKey: "relevant" },
                { id: "minisearch", roleKey: "search_engine", usageKey: "primary" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "css", roleKey: "style_layer", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3", "v4"],
        },
    },
    {
        id: "logra",
        category: "main",
        overlineKey: "main_project_overline",
        titleKey: "logra.title",
        descriptionKey: "logra.description",
        reversed: false,
        primaryAction: { labelKey: "primaryAction", path: "logra" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://getlogra.com",
        },
        githubHref: "https://github.com/tommaso-berti/logra",
        previewProps: {
            url: "https://getlogra.com",
            titleKey: "logra.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
            deferLoad: true,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "vite", roleKey: "build_tooling", usageKey: "relevant" },
                { id: "react-router", roleKey: "routing", usageKey: "relevant" },
                { id: "typescript", roleKey: "application_logic", usageKey: "relevant" },
                { id: "mui", roleKey: "design_system", usageKey: "primary" },
                { id: "framer-motion", roleKey: "style_layer", usageKey: "relevant" },
                { id: "i18next", roleKey: "application_logic", usageKey: "relevant" },
                { id: "tanstack-query", roleKey: "application_logic", usageKey: "relevant" },
                { id: "nodejs", roleKey: "application_logic", usageKey: "primary" },
                { id: "fastify", roleKey: "api_layer", usageKey: "primary" },
                { id: "zod", roleKey: "api_layer", usageKey: "relevant" },
                { id: "mongodb", roleKey: "data_layer", usageKey: "primary" },
                { id: "igdb", roleKey: "data_layer", usageKey: "relevant" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "github-actions", roleKey: "ci_cd", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3"],
        },
    },
    {
        id: "ecommerce-rest-api",
        category: "side",
        overlineKey: "side_project_overline",
        titleKey: "ecommerce-rest-api.title",
        descriptionKey: "ecommerce-rest-api.description",
        reversed: true,
        primaryAction: { labelKey: "primaryAction", path: "ecommerce-rest-api" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://shop.tommasoberti.com",
        },
        githubHref: "https://github.com/tommaso-berti/ecommerce-rest-api",
        previewProps: {
            url: "https://shop.tommasoberti.com",
            titleKey: "ecommerce-rest-api.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
            deferLoad: true,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "vite", roleKey: "build_tooling", usageKey: "relevant" },
                { id: "react-router", roleKey: "routing", usageKey: "relevant" },
                { id: "javascript", roleKey: "application_logic", usageKey: "primary" },
                { id: "mui", roleKey: "design_system", usageKey: "relevant" },
                { id: "tailwindcss", roleKey: "style_layer", usageKey: "support" },
                { id: "nodejs", roleKey: "application_logic", usageKey: "primary" },
                { id: "express", roleKey: "api_layer", usageKey: "primary" },
                { id: "passport", roleKey: "auth_layer", usageKey: "relevant" },
                { id: "express-session", roleKey: "auth_layer", usageKey: "relevant" },
                { id: "postgresql", roleKey: "data_layer", usageKey: "primary" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "github-actions", roleKey: "ci_cd", usageKey: "relevant" },
                { id: "swagger-openapi", roleKey: "api_docs", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3"],
        },
    },
];
