export const projects = [
    {
        id: "portfolio",
        category: "main",
        overlineKey: "main_project_overline",
        titleKey: "portfolio.title",
        descriptionKey: "portfolio.description",
        reversed: false,
        primaryAction: { labelKey: "primaryAction", path: "portfolio" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.tommasoberti.com",
        },
        previewProps: {
            url: "https://www.tommasoberti.com",
            titleKey: "portfolio.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "javascript", roleKey: "application_logic", usageKey: "primary" },
                { id: "mui", roleKey: "design_system", usageKey: "primary" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3"],
        },
    },
    {
        id: "codexpane",
        category: "main",
        overlineKey: "main_project_overline",
        titleKey: "codexpane.title",
        descriptionKey: "codexpane.description",
        reversed: true,
        primaryAction: { labelKey: "primaryAction", path: "codexpane" },
        secondaryAction: {
            labelKey: "secondaryAction",
            href: "https://www.codexpane.tommasoberti.com",
        },
        previewProps: {
            url: "https://www.codexpane.tommasoberti.com",
            titleKey: "codexpane.title",
            overlayLabelKey: "live_preview",
            width: "100%",
            height: 360,
            scale: 0.8,
        },
        details: {
            technologies: [
                { id: "react", roleKey: "core_ui", usageKey: "primary" },
                { id: "javascript", roleKey: "application_logic", usageKey: "primary" },
                { id: "mui", roleKey: "design_system", usageKey: "primary" },
                { id: "tailwindcss", roleKey: "style_layer", usageKey: "relevant" },
                { id: "minisearch", roleKey: "search_engine", usageKey: "primary" },
                { id: "caddy", roleKey: "deployment", usageKey: "relevant" },
                { id: "github", roleKey: "versioning_ci", usageKey: "relevant" },
                { id: "webstorm", roleKey: "development_tooling", usageKey: "support" },
                { id: "css", roleKey: "style_layer", usageKey: "support" },
                { id: "codex", roleKey: "ai_support", usageKey: "support" },
            ],
            roadmapIds: ["v1", "v2", "v3", "v4"],
        },
    },
];
