export const TECHNOLOGIES = {
    react:     { icon: "react",     category: "frontend" },
    vite:      { icon: "vite",      category: "frontend" },
    "react-router": { icon: "react-router", category: "frontend" },
    mui:       { icon: "mui",       category: "frontend" },
    javascript:{ icon: "javascript",category: "frontend" },
    nodejs:    { icon: "nodejs",    category: "backend-runtime" },
    express:   { icon: "express",   category: "backend-runtime" },
    passport:  { icon: "passport",  category: "backend-runtime" },
    "express-session": { icon: "express-session", category: "backend-runtime" },
    postgresql:{ icon: "postgresql",category: "database" },
    github:    { icon: "github",    category: "tools"  },
    "github-actions": { icon: "github-actions", category: "tools" },
    "swagger-openapi": { icon: "swagger-openapi", category: "tools" },
    webstorm:  { icon: "webstorm",  category: "tools"  },
    caddy:     { icon: "caddy",     category: "backend-runtime"  },
    minisearch:{ icon: "minisearch",category: "frontend"},
    tailwindcss:{icon:"tailwindcss",category: "frontend" },
    css:       { icon: "css",       category: "frontend" },
    codex:     { icon: "chatgpt",   category: "tools"  },
};
