export const TECHNOLOGIES = {
    react:     { icon: "react",     category: "frontend" },
    vite:      { icon: "vite",      category: "frontend" },
    "react-router": { icon: "react-router", category: "frontend" },
    "tanstack-query": { icon: "tanstack-query", category: "frontend" },
    "framer-motion": { icon: "framer-motion", category: "frontend" },
    nivo:      { icon: "nivo",      category: "frontend" },
    i18next:   { icon: "i18next",   category: "frontend" },
    mui:       { icon: "mui",       category: "frontend" },
    javascript:{ icon: "javascript",category: "frontend" },
    typescript:{ icon: "typescript",category: "languages-markup" },
    nodejs:    { icon: "nodejs",    category: "backend-runtime" },
    fastify:   { icon: "fastify",   category: "backend-runtime" },
    express:   { icon: "express",   category: "backend-runtime" },
    zod:       { icon: "zod",       category: "backend-runtime" },
    passport:  { icon: "passport",  category: "backend-runtime" },
    "express-session": { icon: "express-session", category: "backend-runtime" },
    auth0:     { icon: "auth0",     category: "backend-runtime" },
    mongodb:   { icon: "mongodb",   category: "database" },
    igdb:      { icon: "igdb",      category: "database" },
    postgresql:{ icon: "postgresql",category: "database" },
    github:    { icon: "github",    category: "tools"  },
    "github-actions": { icon: "github-actions", category: "tools" },
    sentry:    { icon: "sentry",    category: "tools"  },
    pnpm:      { icon: "pnpm",      category: "tools"  },
    "swagger-openapi": { icon: "swagger-openapi", category: "tools" },
    webstorm:  { icon: "webstorm",  category: "tools"  },
    caddy:     { icon: "caddy",     category: "backend-runtime"  },
    minisearch:{ icon: "minisearch",category: "frontend"},
    tailwindcss:{icon:"tailwindcss",category: "frontend" },
    css:       { icon: "css",       category: "frontend" },
    codex:     { icon: "chatgpt",   category: "tools"  },
};
