import { useState } from "react";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { useTranslation } from "react-i18next";
import { getBrandIconDefinition } from "@/config/brandIcons.js";

export default function TechnologySection({ technologies = [] }) {
    const [tab, setTab] = useState("all");
    const { t } = useTranslation("pages", { keyPrefix: "projects" });
    if (!technologies.length) return null;
    const categories = ["all", ...Array.from(new Set(technologies.map((technology) => technology.category))).sort()];
    const filteredTechs = tab === "all" ? technologies : technologies.filter((technology) => technology.category === tab);

    return <Box component="section" id="technologies"><Stack spacing={2.5}><Typography variant="h4">{t("technologiesTitle")}</Typography><Stack direction="row" gap={.5} flexWrap="wrap" sx={{ borderBottom: "1px solid", borderColor: "divider", pb: .75 }}>{categories.map((category) => <Button key={category} onClick={() => setTab(category)} aria-pressed={tab === category} variant="text" sx={{ position: "relative", minHeight: 34, px: 1, color: tab === category ? "text.primary" : "text.secondary", fontSize: ".58rem", textTransform: "uppercase", letterSpacing: ".08em", "&::after": { content: '""', position: "absolute", bottom: -7, left: 7, right: 7, height: 2, bgcolor: "space.blue", transform: tab === category ? "scaleX(1)" : "scaleX(0)", transition: "transform 200ms ease" }, "&:hover": { bgcolor: "action.hover", transform: "translateY(-1px)" } }}>{t(`tech_categories.${category}`)}</Button>)}</Stack><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", md: "repeat(3, 1fr)" }, gap: 1.5 }}>{filteredTechs.map((tech, index) => { const iconDefinition = getBrandIconDefinition(tech.icon); const IconComponent = iconDefinition.component; return <Box component="article" key={`${tech.label}-${index}`} sx={{ minHeight: 176, p: 2, border: "1px solid", borderColor: "divider", bgcolor: "rgba(241,237,227,.64)", transition: "transform 200ms ease, box-shadow 200ms ease, border-color 200ms ease", "&:hover": { transform: "translateY(-3px)", borderColor: "text.secondary", boxShadow: "0 12px 22px rgba(23,32,42,.07)" } }}><Stack direction="row" alignItems="center" gap={1.25}><Box sx={{ width: 38, height: 38, display: "grid", placeItems: "center", border: "1px solid", borderColor: "divider", borderRadius: "50%", bgcolor: "rgba(255,255,255,.45)" }}><IconComponent size={19} color={iconDefinition.color} title={iconDefinition.title || tech.label} /></Box><Box><Typography sx={{ fontWeight: 750 }}>{tech.label}</Typography><Typography sx={{ fontFamily: (theme) => theme.fonts.mono, fontSize: ".52rem", letterSpacing: ".08em", textTransform: "uppercase", color: "text.secondary" }}>{t(`tech_categories.${tech.category}`)}</Typography></Box></Stack>{tech.description ? <Typography variant="body2" color="text.secondary" sx={{ mt: 1.7, lineHeight: 1.55 }}>{tech.description}</Typography> : null}{tech.role || tech.usage ? <Stack spacing={.45} sx={{ mt: 1.2, fontFamily: (theme) => theme.fonts.mono, fontSize: ".52rem", color: "text.secondary" }}>{tech.role ? <Box component="span">{t("role_in_project")} {" // "} {tech.role}</Box> : null}{tech.usage ? <Box component="span">{t("usage_level")} {" // "} {tech.usage}</Box> : null}</Stack> : null}</Box>; })}</Box></Stack></Box>;
}
